version: '3.8'
name: occurrent-148
services:
  events-importer:
    deploy:
      mode: replicated
      replicas: 1
    build: .
    environment:
      MONGO_CONNECTION_STRING: mongodb://test-user:pwd@mongodb:27017/test-db
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    build: mongo/
    hostname: mongodb
    container_name: mongo
    healthcheck:
      test: mongosh mongodb:27017/test --eval 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 0
      start_period: 0s
    ports:
      - "0.0.0.0:27017:27017"
    command: [
      "--auth", "--keyFile", "/mongo.key",
      "--replSet", "rs0", "--bind_ip_all",
    ]
    volumes:
      - ./mongo/init/:/docker-entrypoint-initdb.d/:ro
