version: '3.8'
name: occurrent-148
networks:
  redpanda_network:
    driver: bridge
services:
  events-importer:
    deploy:
      mode: replicated
      replicas: 1
    build: .
    environment:
      MONGO_CONNECTION_STRING: mongodb://test-user:pwd@mongodb:27017/test-db
      KAFKA_BOOTSTRAP_SERVERS: 'redpanda:9092'
  mongo:
    build: mongo/
    hostname: mongodb
    container_name: mongo
    ports:
      - "0.0.0.0:27017:27017"
    command: [
      "--auth", "--keyFile", "/mongo.key",
      "--replSet", "rs0", "--bind_ip_all",
    ]
    volumes:
      - ./mongo/init/:/docker-entrypoint-initdb.d/:ro
